# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 13:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.UUIDField(editable=False, unique=True, verbose_name='일련번호')),
                ('product_cost', models.IntegerField()),
                ('progress', models.CharField(choices=[('requested', '주문 요청'), ('checkout_payment', '결제 확인 중'), ('paid', '결제 완료'), ('failed_payment', '결제 실패'), ('prepared_product', '상품 준비'), ('prepared_delivery', '출고 준비'), ('ongoing_delivery', '배송 중'), ('refund_requested', '반품/환불 요청'), ('done', '거래 완료'), ('canceled', '취소'), ('refunded', '반품/환불 완료'), ('replaced', '교환')], default='requested', max_length=20)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='기타 요청사항')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('decoration', '장식'), ('pan', '팬'), ('roll', '롤')], max_length=20, verbose_name='상품 갈래')),
                ('name', models.CharField(max_length=100, verbose_name='상품명')),
                ('content', models.TextField(verbose_name='설명')),
                ('regular_price', models.PositiveIntegerField(verbose_name='정가')),
                ('selling_price', models.PositiveIntegerField(verbose_name='판매가')),
                ('status', models.CharField(choices=[('active', '정상'), ('sold_out', '품절'), ('obsolete', '단종'), ('deactive', '비활성화')], max_length=20, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ImageField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_route', models.CharField(choices=[('direct', '직접 방문 가입'), ('guestbook', '게스트북'), ('cocoa', '코코아톡'), ('goggle', '고글'), ('navar', '나바')], default='direct', max_length=40, verbose_name='가입 경로')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='shop.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
