# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sn',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='일련번호'),
        ),
    ]
